service: movieapis-lambda

provider:
  name: aws
  runtime: java8
  memorySize: 1536
  timeout: 60

package:
  artifact: target/movie-apis-0.0.1-SNAPSHOT.jar

functions:
  movies-query:
    handler: io.claudio.movieapis.servicehandlers.MoviesQueryLambdaHandler
    events:
      - http:
          path: movies
          method: get
          cors: true
      - http:
          path: movies/{id}
          method: get
          cors: true
  movies-create:
    handler: io.claudio.movieapis.servicehandlers.MoviesCreateLambdaHandler
    events:
      - http:
          path: movies
          method: post
          cors: true
  movies-update:
    handler: io.claudio.movieapis.servicehandlers.MoviesUpdateLambdaHandler
    events:
      - http:
          path: movies/{id}
          method: put
          cors: true
  movies-add-actor:
    handler: io.claudio.movieapis.servicehandlers.MoviesAddActorLambdaHandler
    events:
      - http:
          path: movies/{id}/actor
          method: put
          cors: true
  movies-delete:
    handler: io.claudio.movieapis.servicehandlers.MoviesDeleteLambdaHandler
    events:
      - http:
          path: movies
          method: delete
          cors: true
  actors-query:
    handler: io.claudio.movieapis.servicehandlers.ActorsQueryLambdaHandler
    events:
      - http:
          path: actors
          method: get
          cors: true
      - http:
          path: actors/{id}
          method: get
          cors: true
  actors-add:
    handler: io.claudio.movieapis.servicehandlers.ActorsAddLambdaHandler
    events:
      - http:
          path: actors
          method: post
          cors: true